#file: noinspection YAMLSchemaValidation,SpellCheckingInspection
spring:
  application:
    name: ms-workspace-management
  docker:
    compose:
      enabled: false
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ms_workspace_management}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    schemas: public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI:http://localhost:9000}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAPSERVERS:localhost:9094}
  mail:
    host: smtp.resend.com
    port: 465
    username: resend
    password: ${RESEND_API_KEY:""}
    properties:
      mail.smtp.auth: true
      mail.smtp.ssl.enable: true
#  mail:
#    host: localhost
#    port: 1025
#    properties:
#      mail:
#        smtp:
#          auth: false
#          starttls:
#            enable: false

users:
  kafka:
    topics:
      user-invited: user.invited
      token-revoked: token.revoked
  invite:
    base-url: http://localhost:8082/users/v1
    frontend-url: http://app.switchboard.io
    expiration-hours: 72
  mail:
    from: "Switchboard <onboarding@resend.dev>"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlator}] %-5level %logger{0} - %msg%n"
  level:
    io.github.cassiocintra: DEBUG

info:
  app:
    version: "@project.version@"

server:
  port: 8082
  servlet:
    context-path: /users/v1
